---
# file: roles/gateway/tasks/dns.yml


- name: unbound.conf
  template:
    src: 'unbound.conf.j2'
    dest: '/etc/unbound/unbound.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart unbound

- name: unbound/adservers
  copy:
    src: 'files/etc/unbound/adservers'
    dest: '/etc/unbound/adservers'
    owner: root
    group: root
    mode: 0644

- name: Disable nsd on Hetzner hosts
  ansible.builtin.service:
    name: nsd
    enabled: no 
    state: stopped
  when: provider == "hetzner"

- name: unbound enabled & started
  service:
    name: unbound
    enabled: yes
    state: started
